# Generated by Django 3.2.7 on 2021-10-08 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jugada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combinacion', models.CharField(max_length=14, unique=True)),
                ('pos_est', models.IntegerField()),
                ('pos_real', models.IntegerField()),
                ('unos', models.IntegerField()),
                ('equis', models.IntegerField()),
                ('doses', models.IntegerField()),
                ('mas_probs', models.IntegerField()),
                ('menos_probs', models.IntegerField()),
                ('partido_1', models.CharField(choices=[('1', '1'), ('X', 'X'), ('2', '2')], max_length=1)),
                ('partido_2', models.CharField(choices=[('1', '1'), ('X', 'X'), ('2', '2')], max_length=1)),
                ('partido_3', models.CharField(choices=[('1', '1'), ('X', 'X'), ('2', '2')], max_length=1)),
                ('partido_4', models.CharField(choices=[('1', '1'), ('X', 'X'), ('2', '2')], max_length=1)),
                ('partido_5', models.CharField(choices=[('1', '1'), ('X', 'X'), ('2', '2')], max_length=1)),
                ('partido_6', models.CharField(choices=[('1', '1'), ('X', 'X'), ('2', '2')], max_length=1)),
                ('partido_7', models.CharField(choices=[('1', '1'), ('X', 'X'), ('2', '2')], max_length=1)),
                ('partido_8', models.CharField(choices=[('1', '1'), ('X', 'X'), ('2', '2')], max_length=1)),
                ('partido_9', models.CharField(choices=[('1', '1'), ('X', 'X'), ('2', '2')], max_length=1)),
                ('partido_10', models.CharField(choices=[('1', '1'), ('X', 'X'), ('2', '2')], max_length=1)),
                ('partido_11', models.CharField(choices=[('1', '1'), ('X', 'X'), ('2', '2')], max_length=1)),
                ('partido_12', models.CharField(choices=[('1', '1'), ('X', 'X'), ('2', '2')], max_length=1)),
                ('partido_13', models.CharField(choices=[('1', '1'), ('X', 'X'), ('2', '2')], max_length=1)),
                ('partido_14', models.CharField(choices=[('1', '1'), ('X', 'X'), ('2', '2')], max_length=1)),
                ('pleno15_local', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('M', 'M')], max_length=1)),
                ('pleno15_visitante', models.CharField(choices=[('0', '0'), ('1', '1'), ('2', '2'), ('M', 'M')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.CharField(max_length=9)),
                ('jornada', models.CharField(max_length=2)),
                ('orden_partido', models.IntegerField()),
                ('dia', models.CharField(max_length=3)),
                ('hora', models.CharField(max_length=5)),
                ('local', models.CharField(max_length=30)),
                ('visitante', models.CharField(max_length=30)),
                ('prob_real_1', models.DecimalField(decimal_places=0, max_digits=2)),
                ('prob_real_X', models.DecimalField(decimal_places=0, max_digits=2)),
                ('prob_real_2', models.DecimalField(decimal_places=0, max_digits=2)),
                ('prob_est_1', models.DecimalField(decimal_places=0, max_digits=2)),
                ('prob_est_X', models.DecimalField(decimal_places=0, max_digits=2)),
                ('prob_est_2', models.DecimalField(decimal_places=0, max_digits=2)),
                ('rentabilidad_1', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rentabilidad_X', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rentabilidad_2', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='PartidoPleno15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.CharField(max_length=9)),
                ('jornada', models.CharField(max_length=2)),
                ('dia', models.CharField(max_length=3)),
                ('hora', models.CharField(max_length=5)),
                ('local', models.CharField(max_length=30)),
                ('visitante', models.CharField(max_length=30)),
                ('prob_real_local_0', models.DecimalField(decimal_places=0, max_digits=2)),
                ('prob_real_local_1', models.DecimalField(decimal_places=0, max_digits=2)),
                ('prob_real_local_2', models.DecimalField(decimal_places=0, max_digits=2)),
                ('prob_real_local_M', models.DecimalField(decimal_places=0, max_digits=2)),
                ('prob_real_visitante_0', models.DecimalField(decimal_places=0, max_digits=2)),
                ('prob_real_visitante_1', models.DecimalField(decimal_places=0, max_digits=2)),
                ('prob_real_visitante_2', models.DecimalField(decimal_places=0, max_digits=2)),
                ('prob_real_visitante_M', models.DecimalField(decimal_places=0, max_digits=2)),
                ('prob_est_local_0', models.DecimalField(decimal_places=0, max_digits=2)),
                ('prob_est_local_1', models.DecimalField(decimal_places=0, max_digits=2)),
                ('prob_est_local_2', models.DecimalField(decimal_places=0, max_digits=2)),
                ('prob_est_local_M', models.DecimalField(decimal_places=0, max_digits=2)),
                ('prob_est_visitante_0', models.DecimalField(decimal_places=0, max_digits=2)),
                ('prob_est_visitante_1', models.DecimalField(decimal_places=0, max_digits=2)),
                ('prob_est_visitante_2', models.DecimalField(decimal_places=0, max_digits=2)),
                ('prob_est_visitante_M', models.DecimalField(decimal_places=0, max_digits=2)),
                ('rentabilidad_local_0', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rentabilidad_local_1', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rentabilidad_local_2', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rentabilidad_local_M', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rentabilidad_visitante_0', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rentabilidad_visitante_1', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rentabilidad_visitante_2', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rentabilidad_visitante_M', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                'verbose_name_plural': 'Partidos pleno 15',
            },
        ),
    ]
